name: Deploy to Web Host

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4' # Specify the PHP version you need

    - name: Sync files via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: './your-theme-directory' # Update with your theme directory
        remote-dir: '/path-to-your-wordpress/wp-content/themes/your-theme' # Update with the remote directory

    - name: Finalize deployment
      run: echo "Deployment complete!"
